In [5]:
 for x in range(3,19,3):
     print (x)
     

3
6
9
12
15
18


In [11]:
thislist=['apple','banana','cherry','strawberry']
print(thislist[2])
thislist.append('mango')
print(thislist)
temp=thislist[3]
thislist[3]=thislist[4]
thislist[4]=temp
print(thislist)

cherry
['apple', 'banana', 'cherry', 'strawberry', 'mango']
['apple', 'banana', 'cherry', 'mango', 'strawberry']


In [1]:

list1=list(map(float,input("Enters the number seperated by spaces: ").split()))


print(list1)
print(max(list1))
print(min(list1))
avg=sum(list1)/len(list1)
print(avg)
spec=float(input("Enter a number to count its occurences"))
count=list1.count(spec)
print(f"The number {spec} has occured {count} times")

Enters the number seperated by spaces:  5


[5.0]
5.0
5.0
5.0


Enter a number to count its occurences 5


The number 5.0 has occured 1 times


In [2]:
import numpy as np
a=np.array({5,67,5,10,11})
print(a)


{67, 10, 11, 5}


In [4]:
import numpy as np
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)


[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [7]:
import numpy as np
np.zeros(10)
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
arr=np.array([[1,2,3,4],[6,7,8,9],[10,11,12,13]])
arr=np.array(data2)
print(arr)
print(arr.ndim)
print(arr.shape)


[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [ ]:
matrix1=np.random.randint(1,51,size=(3,3))
matrix2=np.random.randint(1,51,size=(3,3))

matrix_addition=matrix1+matrix2
matrix_subtraction=matrix1-matrix2
matrix_multiplication=matrix1*matrix2
matrix_dot_product=np.dot(matrix1,matrix2)


In [10]:
import numpy as np
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [16]:
vector=np.random.randint(100,490,size=(20))
print(matrix1)

[264 145 367 342 322 380 318 396 237 397 178 130 185 393 231 324 392 247
 292 390]


In [29]:
vector=np.random.randint(100,400,size=(10))
print(vector)
rev=np.flip(vector)
print(rev)

[259 191 361 135 239 271 200 123 214 125]
[125 214 123 200 271 239 135 361 191 259]


In [31]:
matrix1=np.random.randint(0,8,size=(3,3))
print(matrix1)

[[7 2 3]
 [6 5 1]
 [6 4 2]]


In [33]:
matrix=np.random.randint(1,2,size=(3,3))
print(matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [35]:
matrix1=np.random.randn(3,3,3)
print(matrix1)

[[[-0.04540009 -0.84962968  0.16881954]
  [-0.85553732  0.93528008  1.41635031]
  [-2.5615929   0.87597829  2.45532948]]

 [[ 0.62018746  0.75555959 -0.45465277]
  [ 1.49107487 -0.01439052 -1.42233459]
  [ 0.00323196 -1.3706229   1.01430095]]

 [[ 0.42242043 -0.69549943  1.22555102]
  [-0.98503059 -0.53387361  0.19152154]
  [-0.47433535  1.09980851  1.53510361]]]


In [15]:
import pandas as pd

temp = [22, 24, 21, 23, 25, 20, 19]
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
t_s = pd.Series(temp, index = days)
a_t = t_s.mean()
print(f"Average temp for the week: {a_t: .2f}*C")

max_t = t_s.max()
min_t = t_s.min()
max_d = t_s.idxmax()
min_d = t_s.idxmin()

print(f"Max temp: {max_t} on {max_d}")
print(f"Min temp: {min_t} on {min_d}")

t = int(input("Enter Temperature: "))
av = t_s[t_s > t]
print(f"Temp greater than {t}*C\n{av}")

f = (t_s * 9/5 + 32)
print("Temp in Fahrenheit: ", f)

a = t_s[t_s > a_t]
print("Days with temp above avg:\n", a)

Average temp for the week:  22.00*C
Max temp: 25 on Friday
Min temp: 19 on Sunday


Enter Temperature:  30


Temp greater than 30*C
Series([], dtype: int64)
Temp in Fahrenheit:  Monday       71.6
Tuesday      75.2
Wednesday    69.8
Thursday     73.4
Friday       77.0
Saturday     68.0
Sunday       66.2
dtype: float64
Days with temp above avg:
 Tuesday     24
Thursday    23
Friday      25
dtype: int64


In [19]:
import pandas as pd

data = {
    'Roll Number': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Name': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    'Gender': ['M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F'],
    'Marks1': [85, 78, 92, 88, 76, 95, 89, 74, 81, 90],
    'Marks2': [45, 38, 50, 42, 35, 48, 47, 40, 39, 49],
    'Marks3': [90, 85, 88, 92, 87, 91, 89, 84, 86, 93]
}
df = pd.DataFrame(data)
print(df)
df['Total Marks'] = df['Marks1'] + df['Marks2'] + df['Marks3']

lm1 = df['Marks1'].min()
print("Lowest marks in Marks 1: ", lm1)

hm2 = df['Marks2'].max()
print("Highest marks in Marks 2: ", hm2)

am3 = df['Marks3'].mean()
print("Average Marks: %.2f" % am3)

df['Average'] = df['Total Marks'] / 3

ha = df.loc[df['Average'].idxmax(), 'Name']
print("Student with higest average: ", ha)

fs = df[df['Marks2'] < 40]
print("Number of failed students: ", len(fs))
    
    

   Roll Number Name Gender  Marks1  Marks2  Marks3
0            1    A      M      85      45      90
1            2    B      F      78      38      85
2            3    C      M      92      50      88
3            4    D      F      88      42      92
4            5    E      M      76      35      87
5            6    F      F      95      48      91
6            7    G      M      89      47      89
7            8    H      F      74      40      84
8            9    I      M      81      39      86
9           10    J      F      90      49      93
Lowest marks in Marks 1:  74
Highest marks in Marks 2:  50
Average Marks: 88.50
Student with higest average:  F
Number of failed students:  3


In [2]:
import  numpy as np
int_0_to_100=np.arange(101)
print(int_0_to_100)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [6]:
n=5
for i in range(1,n+1):
    for j in range(1,i+1):
      print(j,end=" ")
    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [8]:
import numpy as np
x=np.ones((7,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
number=int(input("Enter a number: "))
total_sum=sum(range(1,number+1))
print(f"The sum of all numbers from 1 to {number} is {total_sum}.")

Enter a number:  8


The sum of all numbers from 1 to 8 is 36.


In [12]:
import numpy as np
array=np.arange(100,200,10).reshape(5,2)
print(array)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]
